project:
  type: website

website:
  title: "CRT in AI Newsletter"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/crt_ai
      - icon: youtube
        href: https://www.youtube.com/@crt-aimedia2559
      - icon: envelope-fill
        href: mailto:janetchoi@ucc.ie
format:
  html:
    theme: united
    css: styles.css

editor: visual

